before:
  hooks:
    - rm -rf dist/

builds:
  - main: ./...
    id: mise-seq
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: mise-seq
    builds:
      - mise-seq
    format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: hiono
    name: mise-seq
