project_name: mise-seq

before:
  hooks:
    - rm -rf dist/

builds:
  - id: mise-seq
    dir: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: mise-seq
    builds:
      - mise-seq
    format: tar.gz

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: hiono
    name: mise-seq
