project_name: mise-seq

before:
  hooks:
    - rm -rf dist/

builds:
  - id: mise-seq
    dir: .
    binary: mise-seq
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .CommitDate }}

archives:
  - id: mise-seq
    builds:
      - mise-seq
    format: tar.gz

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: hiono
    name: mise-seq
