project_name: mise-seq

archives:
  - id: mise-seq
    formats:
      - tar.gz
      - zip

builds:
  - id: mise-seq
    main: ./...
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: hiono
    name: mise-seq
